# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'conf.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from dbmgr import DbManager

class Ui_childWidget(QtWidgets.QWidget):

    def setupUi(self, childWidget):
        childWidget.setObjectName("childWidget")
        childWidget.resize(515, 900)
        self.gridLayout_2 = QtWidgets.QGridLayout(childWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(childWidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.shopNameLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.shopNameLineEdit.setObjectName("shopNameLineEdit")
        self.horizontalLayout.addWidget(self.shopNameLineEdit)
        self.addShopBtn = QtWidgets.QPushButton(self.groupBox)
        self.addShopBtn.setObjectName("addShopBtn")
        self.horizontalLayout.addWidget(self.addShopBtn)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(childWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.shopNameComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.shopNameComboBox.setObjectName("shopNameComboBox")
        self.gridLayout.addWidget(self.shopNameComboBox, 0, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.srcColLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.srcColLineEdit.setObjectName("srcColLineEdit")
        self.gridLayout.addWidget(self.srcColLineEdit, 1, 1, 1, 3)
        self.addMapBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.addMapBtn.setObjectName("addMapBtn")
        self.gridLayout.addWidget(self.addMapBtn, 1, 4, 2, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.tagColLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.tagColLineEdit.setObjectName("tagColLineEdit")
        self.gridLayout.addWidget(self.tagColLineEdit, 2, 1, 1, 3)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 2)
        self.colNumSpinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.colNumSpinBox.setObjectName("colNumSpinBox")
        self.gridLayout.addWidget(self.colNumSpinBox, 3, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(177, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 4, 1, 1)
        self.rowNumSpinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.rowNumSpinBox.setObjectName("rowNumSpinBox")
        self.gridLayout.addWidget(self.rowNumSpinBox, 3, 5, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(childWidget)
        self.tableView.setObjectName("tableView")
        self.gridLayout_2.addWidget(self.tableView, 2, 0, 1, 1)

        self.retranslateUi(childWidget)
        QtCore.QMetaObject.connectSlotsByName(childWidget)
        self.addShopBtn.clicked.connect(self.on_addShopBtn_clicked)

    def on_addShopBtn_clicked(self):
        shop_name = self.shopNameLineEdit.text()
        if not len(shop_name) > 0:
            msgbox = QtWidgets.QMessageBox(QtWidgets.QMessageBox.critical,"错误","未正确填写店铺名字")
            y = msgbox.addButton("是",QtWidgets.QMessageBox.Yes)
            if msgbox.clickedButton() == y:
                return
        dbMgr = DbManager("tablehead.db")
        conn = dbMgr.getconn()
        cur = conn.cursor()
        insert_sql = "INSERT INTO SHOP(SHOP_NAME) VALUES ({})".format(shop_name)
        cur.execute(insert_sql)
        res = cur.fetchone()
        print(res)
    def retranslateUi(self, childWidget):
        _translate = QtCore.QCoreApplication.translate
        childWidget.setWindowTitle(_translate("childWidget", "表头映射配置"))
        self.groupBox.setTitle(_translate("childWidget", "添加店铺"))
        self.label.setText(_translate("childWidget", "店铺名："))
        self.shopNameLineEdit.setPlaceholderText(_translate("childWidget", "请输入需要添加的店铺名称"))
        self.addShopBtn.setText(_translate("childWidget", "新增店铺"))
        self.groupBox_2.setTitle(_translate("childWidget", "新增店铺列名映射"))
        self.label_4.setText(_translate("childWidget", "选择店铺名："))
        self.label_2.setText(_translate("childWidget", "店铺表列名："))
        self.srcColLineEdit.setPlaceholderText(_translate("childWidget", "请输入要映射的店铺表头"))
        self.addMapBtn.setText(_translate("childWidget", "新增映射"))
        self.label_3.setText(_translate("childWidget", "汇总表列名："))
        self.tagColLineEdit.setPlaceholderText(_translate("childWidget", "请输入要映射的汇总表头"))
        self.label_5.setText(_translate("childWidget", "汇总表日期列号："))
        self.label_6.setText(_translate("childWidget", "汇总表表头行号："))
